# Generated by Django 5.0.3 on 2024-05-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_cliente',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_empleado',
        ),
    ]
