# Generated by Django 5.0.3 on 2024-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuario', '0003_cargo_cliente_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
