# Generated by Django 5.0.3 on 2024-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_remove_ordencompraproducto_orden_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompraproducto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
