# Generated by Django 5.0.3 on 2024-05-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0007_alter_ordencompraproducto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesPayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corre', models.EmailField(max_length=254)),
                ('forma_Pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_paypal', to='tiendaApp.forma_pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.DateField()),
                ('codigo_seguridad', models.CharField(max_length=4)),
                ('forma_Pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_tarjeta', to='tiendaApp.forma_pago')),
            ],
        ),
    ]
