# Generated by Django 5.0.3 on 2024-05-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0008_detallespaypal_detallestarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallespaypal',
            old_name='corre',
            new_name='correo',
        ),
    ]
